in_features: 528
mlp_features:
- 384
hidden_size: 128
num_layers: 6
num_heads: 4
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: 100
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
depthwise_conv_kernel_size: 31
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
